### ISSUE TITLE
superagent-no-cache use error 

### ISSUE THREAD

**Issue by zhoudaqing** [johntron/superagent-no-cache#21]
const nocache = require('superagent-no-cache');
const request = require('superagent');

request
.get('/test')
.use(nocache)
.end(function(err, res){
});

error:
========================================
/Users/akk/sourcecode/test/node_modules/component-ie/index.js:16
el = document.createElement('b'),
^

ReferenceError: document is not defined
at ie (/Users/akk/sourcecode/test/node_modules/component-ie/index.js:16:26)
at Object. (/Users/akk/sourcecode/test/node_modules/component-ie/index.js:5:18)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/Users/akk/sourcecode/test/node_modules/superagent-no-cache/index.js:1:72)

Process finished with exit code 1

**Comment by johntron** [comment]
This error would be eliminated by using the alternative method described here: #23. @zhoudaqing - does this solve your problem?

**Comment by shinta5150** [comment]
Getting this error as well even after adding the #23

**Comment by johntron** [comment]
@shinta5150 help me reproduce it. If you're still getting this error, you're either not using #23, you haven't rebuilt, or you're trying to do something like use component-ie in nodejs.

**Comment by Floriangomis** [comment]
It might be because as me you are not using it in a browser environnement so you don't have access to document object ?

**Comment by mackenzie-orange** [comment]
Because #23 resolves this issue, could `superagent-no-cache` get an npm release?
